### ISSUE TITLE
Add randomly generated id and class for injected anchor and image tags

### ISSUE THREAD

**Issue by joshterrill** [joshterrill/adswap#1]
https://github.com/joshterrill/adswap/blob/219ce58b3aff6450b6108e45c4bc3b49542c0e89/views/js/client.js#L21

The line of code referenced needs to have a randomly generated `id` and `class` both on the `<a/>` and `<img/>` tags. All the generated attributes need to be different from each other. I thought it might be good to implement some sort of guid generator function and use that. Something like this:

```javascript
function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4();
}
```

And then use create an instance of `guid()` for each of the attribute values.

### Note: You will need to disable adblock on github in order to view this repo.

**Comment by sasalx** [comment]
I can take this.

**Comment by joshterrill** [comment]
Fixed in https://github.com/joshterrill/adswap/pull/2.
